default: &default
  # host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  host: localhost
  database: dev
  host: localhost

test:
  <<: *default
  host: localhost
  database: test

production:
  <<: *default
  database: prod
  host: db
